version: 2
updates:
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    # directories with dockerfiles
    directories:
      - "/base"
      - "/buildah"
      - "/deploy"
      - "/dotnet-6.0"
      - "/java"
      - "/k8s-tools"
      - "/node"
      - "/playwright"
    schedule:
      interval: "weekly"
