ARG BASE_IMG=ghcr.io/domstolene/openshift-actions-runners/runner:latest
FROM $BASE_IMG AS runner

USER root

ARG KUBERNETES_RELEASE=v1.34.2
RUN curl -LO https://dl.k8s.io/release/${KUBERNETES_RELEASE}/bin/linux/amd64/kubectl
RUN sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

RUN dnf -y upgrade --security && \
    dnf -y install \
    openldap-clients \
    iputils \
    samba-client \
    wget \
    unzip \
    gettext-envsubst \
    java-21-openjdk-devel \
    python3-winrm && \
    dnf clean all

ARG MAVEN_VERSION=3.9.16
RUN curl -fsSL https://dlcdn.apache.org/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz -o apache-maven-${MAVEN_VERSION}-bin.tar.gz && \
    tar xzf apache-maven-${MAVEN_VERSION}-bin.tar.gz -C /opt && \
    rm apache-maven-${MAVEN_VERSION}-bin.tar.gz
ENV JAVA_HOME=/usr/lib/jvm/java
RUN sudo ln -s /opt/apache-maven-${MAVEN_VERSION}/bin/mvn /usr/local/bin/mvn
RUN mvn -version

RUN sudo chmod 4711 /usr/bin/ping
USER $UID
