ARG BASE_IMG=quay.io/redhat-github-actions/runner:latest
FROM $BASE_IMG AS java-runner

USER root

# java-latest-openjdk-devel tracks the newest OpenJDK available in Fedora
RUN dnf install -y java-latest-openjdk-devel

USER $UID
