ARG BASE_IMG=quay.io/redhat-github-actions/runner:latest
FROM $BASE_IMG AS node-runner

USER root

# https://nodejs.org/en/download/package-manager
# 22 is LTS (active until April 2027)
RUN dnf install -y nodejs22 nodejs22-npm

USER $UID
