ARG BASE_IMG=quay.io/redhat-github-actions/runner:latest
FROM $BASE_IMG AS k8s-tools-runner

USER root

ARG HELM_VERSION="3.21.2"
ENV HELM_VERSION=${HELM_VERSION}

ARG KN_VERSION="1.9.2"
ENV KN_VERSION=${KN_VERSION}

ARG OC_VERSION="stable"
ENV OC_VERSION=${OC_VERSION}

ARG TKN_VERSION="1.11.0"
ENV TKN_VERSION=${TKN_VERSION}

ARG YQ_VERSION="4.44.6"
ENV YQ_VERSION=${YQ_VERSION}

COPY ./install-tools.sh .

RUN ./install-tools.sh
RUN rm ./install-tools.sh

USER $UID
